{{if .Values.gateway.enabled -}}
---
apiVersion: policy.linkerd.io/v1alpha1
kind: Server
metadata:
  namespace: {{.Values.namespace}}
  name: linkerd-gateway
  labels:
    linkerd.io/extension: multicluster
  annotations:
    {{ include "partials.annotations.created-by" . }}
spec:
  podSelector:
    matchLabels:
      app: linkerd-gateway
  port: linkerd-proxy
  proxyProtocol: TLS
---
apiVersion: policy.linkerd.io/v1alpha1
kind: ServerAuthorization
metadata:
  namespace: {{.Values.namespace}}
  name: linkerd-gateway
  labels:
    linkerd.io/extension: multicluster
  annotations:
    {{ include "partials.annotations.created-by" . }}
spec:
  server:
    name: linkerd-gateway
  client:
    meshTLS:
      identities:
      - '*'
{{end -}}
